spring:
  application:
    name: XK-AUTHORITY-API
  profiles:
    active: dev
  datasource:
    druid:
      initialSize: 5 #初始化连接大小
      minIdle: 5     #最小连接池数量
      maxActive: 20  #最大连接池数量
      maxWait: 60000 #获取连接时最大等待时间，单位毫秒
      timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000   #配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 from DUAL  #测试连接
      testWhileIdle: true                  #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      testOnBorrow: false                  #获取连接时执行检测，建议关闭，影响性能
      testOnReturn: false                  #归还连接时执行检测，建议关闭，影响性能
      poolPreparedStatements: false        #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      maxPoolPreparedStatementPerConnectionSize: 20 #开启poolPreparedStatements后生效
      filters: stat,wall #配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
      connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000' #通过connectProperties属性来打开mergeSql功能;慢SQL记录
    #配置数据库连接池为druid
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: com.mmmgdzl.test.springcloudsecurityauth.pojo
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名,l_name -> lName
    jdbc-type-for-null: NULL
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    cache-enabled: true #开启二级缓存
    call-setters-on-nulls: true #map空列不显示问题
  mapper-locations:
  - classpath:mapper/*.xml
info:
  app:
    name: "@project.name@"
    description: ${eureka.instance.instance-id}
    version: "@project.version@"
eureka:
  instance:
    prefer-ip-address: true
    instance-id: 授权服务
  client:
    service-url:
      defaultZone: http://mmmgdzl:9879871221@${eureka.instance.hostname}:8000/eureka/
---
server:
  port: 8100
spring:
  profiles: dev
  #配置数据源
  datasource:
    #配置数据库url
    url: jdbc:mysql://localhost:3306/learnspringcloudsecurityoauth2?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    #配置数据库用户名
    username: root
    #配置数据库密码
    password: 9879871221..s.k
  #配置redis
  redis:
    #配置redis服务器地址
    host: 192.168.25.132
    #配置redis服务器端口
    port: 6379
    #配置redis密码
    password: 9879871221
eureka:
  instance:
    hostname: 127.0.0.1
