spring:
  application:
    #服务名称(服务注册到eureka名称)
    name: XK-RESOURCE-API
  profiles:
    #当前启用文件配置块
    active: dev
#feign:
#  hystrix:
#    enabled: true
#  client:
#    config:
#      default:
#        connectTimeout: 10000
#        readTimeout: 5000
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            #设置超时时间为10s
#            timeoutInMilliseconds: 10000
#info:
#  app:
#    name: "@project.name@"
#    description: ${eureka.instance.instance-id}
#    version: "@project.version@"
#服务注册到eureka地址
eureka:
  instance:
    #服务实例名称
    instance-id: 资源接口
    #显示服务ip地址转换
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://mmmgdzl:9879871221@${eureka.instance.hostname}:8000/eureka/
    register-with-eureka: true
    fetch-registry: true
security:
  oauth2:
    client:
      grant-type: client_credentials
    resource:
      prefer-token-info: false
---
#服务启动端口号
server:
  port: 8101
spring:
  profiles: dev
#服务注册到eureka地址
eureka:
  instance:
    #服务主机地址
    hostname: 127.0.0.1
    #服务心跳包间隔
    lease-renewal-interval-in-seconds: 2
    #服务剔除等待时长
    lease-expiration-duration-in-seconds: 5
security:
  oauth2:
    client:
      client-id: SYSTEM
      client-secret: 123456
      access-token-uri: http://localhost:8002/auth/oauth/token
    resource:
      user-info-uri: http://localhost:8002/auth/api/member
